### PR TITLE
fix spec to build on rawhide buildroot

### PR DESCRIPTION
**Pull request by mefuller**
Updated the spec to build properly in rawhide chroot (mock):

https://bugzilla.redhat.com/show_bug.cgi?id=2126785
https://copr.fedorainfracloud.org/coprs/fuller/usbrelay/build/4994082/

### CODE REVIEW

**Comment by mefuller** [comment]
Updated builds:
https://copr.fedorainfracloud.org/coprs/fuller/usbrelay/build/4994873/

Bug also updated

**Comment by darrylb123** [comment]
I see there are a heap more problems found.
I'll start on them tomorrow.

What delimits the end of the description? He says that some things are
inadvertently in the description.

I'll also test the Requires: hidapi business.

The license problems must be due to the tar file he's got, since it is in
the git repo (I believe). I'll check this out too.

I've never seen the error regarding late group creation.

Darryl

**Comment by darrylb123** [comment]
Just thinking about the license issue and why he was seeing something
different to GitHub.
With last couple of changes I have maintained release 1.1 so it doesn't
break your spec file.
I do that by deleting the release, then the 1.1 tag. I then create a new
1.1 tag and release. The updated licenses were handled this way, therefore
usbrelay-1.1.tar.gz has different contents!!!

When I did my tests, I used spectool to pull a fresh tar.gz file before I
started.

If you used the tar file from before the license changes, yours would not
have the updates???

Darryl

**Comment by mefuller** [comment]
I had no idea you were doing that. 
It probably messed up things on my end

**Comment by darrylb123** [comment]
Sorry,
how do you want it done in future?
The only changes I can see happening (other than the spec file) is to
address whatever concerns with the licenses. I can do point releases
(1.1.x) but then the spec file would need to change with it???
I just assumed you were pulling the source each time so minor changes to
things like licenses, re-releasing seemed the simplest.
Happy to do whatever you need...

Darryl

**Comment by darrylb123** [comment]
Working on the license issue.
It seems the MIT license file usbrelay_py arrived at some point in the
past. It doesn't apply to anything as all the files are explicitly GPL2+
I have deleted it from the repo

Do you want:
- A new release 1.1 with the licences sorted. You will need to grab the tar
file again.
- A new release tagged 1.1.1 and fix the spec file to suit.

PS
I worked out the %description delimiter (another %tag)
and tested removing Requires: hidapi (which works correctly, still
requiring hidapi when installing).

Working my way through the rest.

Darryl

**Comment by darrylb123** [comment]
Mark,
*I have fixed a bunch of the issues.*
2,7 &16: Worked out how the delimiters work in %description and fixed.
- Moved the Requires: systemd-udev to the top tags
- tested that hidapi is automatically required without a specific tag

5: Removed the usbrelay_py/LICENSE file. Not used. This will require new
source tar.gz. See previous email

12: Done? Used explicit path to file for py3_shebang_fix. Seems to add
flags to the usbrelayd shebang (#! /usr/bin/python3 -sP) which I assume is
what he is talking about.

25: Done

26: Done Added -py to the python3usbrelay-py subpackage

29: Done Stopped the usbrelayd service starting at all. It should be
started by udev when a compatible relay is plugged in. Tested and seems to
be working fine.

*Issues I have not fixed yet*

21: Signature verification. I have no intention of using it. Michal added
it and may have a use for it. I shall add some comments about that for
Bjorn on the bug.

27: Not really sure how to approach this. You had to
remove %generate_buildrequires to build on rawhide. Is it a rawhide bug or
will it be like that forever...

28: I've fiddled with this quite a bit without success. The group is
created all right, and isn't deleted when the package is removed. This is
why I didn't see the error, subsequent installs don't error.
Bjorn also didn't know so I hope he gets some response from the devel list.
Note that if usbrelay is installed first then the rest installed
afterwards, the error doesn't occur as the group is added by usbrelay and
runs through to completion.
I even tried running the macro on both packages thus:
%pre
%sysusers_create_compat usbrelay.sysusers

%pre -n %{name}-mqtt
%sysusers_create_compat usbrelay.sysusers

Please let me know what you want to do with the source version.
Darryl

**Comment by darrylb123** [comment]
Mark,
I received some advice from Bjorn regarding 28 and have included it.
It now does not warn installing all packages together.
It was basically a %pre script to do a groupadd usbrelay in the mqtt
package.
I have asked if the practice is to remove the group when the package is
deleted.

Please use
spectool -g -R SPECS/usbrelay.spec
to get the latest source from GitHub.

**Comment by mefuller** [comment]
Thanks for the updates. I've been traveling and may get to it next week, Thursday at the earliest.

Nov 10, 2022 11:38:18 Darryl Bond ***@***.***>:

> Mark,
> I received some advice from Bjorn regarding 28 and have included it.
> It now does not warn installing all packages together.
> It was basically a %pre script to do a groupadd usbrelay in the mqtt
> package.
> I have asked if the practice is to remove the group when the package is
> deleted.
> 
> Please use
> spectool -g -R SPECS/usbrelay.spec
> to get the latest source from GitHub.
> 
>

**Pull request merged**
