### PR TITLE
Improve makefile

### PR DESCRIPTION
**Pull request by herve0742**
I need to launch make with custom variables like LIBDIR, PREFIX, and to have a pkgconfig file.
So I propose these commits to be added to the master branch.

### CODE REVIEW

**Comment by darrylb123** [comment]
You'll have to excuse my ignorance. I know nothing about pkgconfig until I read a little about it today. I still do not understand what it does for usbrelay. That said, that is no reason to reject your changes.

Your changes break the rpm build because of the file /usr/lib64/pkgconfig/libusbrelay.pc

On my fedora system there are a few .pc files in /usr/lib64/pkgconfig mainly to do with python so I need to decide what to do about the breakage. I need to fix that quickly if I pull in your changes.
First of all, what do you recommend?

**Comment by herve0742** [comment]
Following my guess, I add this commit in the hope that it will do the job. I haven't tested it, let me know the result.

**Comment by darrylb123** [comment]
I see Fedora has a recommendation to use pkgconfig if you've got it. I'll
try it later. Your patch looks like it would do the trick.

I'll try it later.

Darryl

**Comment by darrylb123** [comment]
Yes, that works nicely. 
https://docs.fedoraproject.org/en-US/packaging-guidelines/PkgConfigBuildRequires/
This was not required as it builds the library too.

I shall merge you changes.

**Pull request merged**
