### PR TITLE
Command line parser improvements

### PR DESCRIPTION
**Pull request by wentasah**
I find working with the program quite difficult, because of unusual
command line handling. This is a first step to improve the command
line parser and make it more similar to many GNU/Linux programs. These
commits add long options and --help, but otherwise, the command line
handling stays backward compatible.

In future commits, I plan to extend both the options and the help. My
intention is to add at least an explicit option for changing relay ID.

### CODE REVIEW

**Comment by darrylb123** [comment]
Pulled... This is really nice. I have never seen argp before.
Happy for the change to the serial to be handled this way. Go ahead.

sudo LD_LIBRARY_PATH=. ./usbrelay --debug  --help
Usage: usbrelay [OPTION...] [ACTION...]
Control or query USB HID relays.

  -d, --debug                Produce debugging output
  -q, --quiet                Be quiet
  -?, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version

Without ACTION, the actual state of all relays is printed to stdout.
ACTION can be one of:
RELID_N=[0|1] to switch the N-th relay off or on
RELID=NEWID to change relay ID

Report bugs to https://github.com/darrylb123/usbrelay/issues

**Comment by darrylb123** [comment]
Michal,
A new issue was raised. Building on Manjaro uses the zip file rather than a git clone. The build fails on gitversion.c because there is no git metadata in the zip file.
I have added a git hook to create gitversion.c so that is is added with the zip file. 
The problem is that the hook is pre-commit so that the gitversion.c is updated and added to the commit. The gitversion.c is therefore always 1 commit prior to the actual commit. It's not a big problem but you might know of a better way.

Darryl

**Comment by darrylb123** [comment]
Michal,
Please disregard my last message. I've changed the message printed by -V to the commit number which will do for my purposes. The commit number is also logged so that it can be matched.

Darryl

**Comment by wentasah** [comment]
> Please disregard my last message.

OK, but I have few comments. I'll mention them in #52.

**Pull request merged**
