### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by wentasah**
Please see individual commit messages for more detailed description.

### CODE REVIEW

**Comment by darrylb123** [comment]
Michael,
Would you believe I committed a bug fix only yesterday that fixes at least
one of your fixes. Can you debase on that and apply the others.

Darryl

**Comment by wentasah** [comment]
Here you're with two non-conflicting commits. I'll probably send you some comments related to the remaining patches after I test your fixes.

Thanks.

**Comment by darrylb123** [comment]
One of my fixes was to not print anything except the permission denied
message. I expanded to error message to how to resolve the issue.

**Comment by darrylb123** [comment]
Michael,
Sorry about the run around. Looked at your diff on a phone.
It showed a diff against my changed code and I was confused.
Your code looks ok to merge and doesn't conflict. I'll test.

**Comment by darrylb123** [comment]
I've merged your code.
I really do need to learn how to use git properly. I wanted to pull your
changes in turn to look and test them.

Ended up going by the diff in github to merge then test.

Darryl

**Pull request merged**
